apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # Change this to a secure password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage1
          mountPath: /var/lib/mysql2
      volumes:
      - name: mysql-storage1
        persistentVolumeClaim:
          claimName: mysql-pvc1

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
#    nodePort: 30036  # Choose a port in the 30000-32767 range
  type: NodePort  # This exposes the service on a node port

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-load
  namespace: dify
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql-service-load
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc1
  namespace: mysql
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
